events { }
http {
  server {
    listen 80;
    location / {
      resolver 127.0.0.1;
      proxy_pass http://app:80;
    }

    location /api/ {
      resolver 127.0.0.1;
      proxy_pass http://server:3001/api/;
    }
  }
}
